---
classes:
  - '::docker'
  - '::fuel_project::common'
  - '::fuel_project::jenkins::slave'
  - '::fuel_project::jenkins::slave::iso_build'
  - '::fuel_project::jenkins::slave::package_build'
  - '::fuel_project::jenkins::slave::run_tests'
  - '::fuel_project::jenkins::slave::gather_jobs_resources'
  - '::sudo'
  - '::sysctl::base'

# docker configuration
docker::package_name: docker-engine
docker::version: 1.12.1-0~trusty
docker::docker_users:
  - jenkins
docker::use_upstream_package_source: false

# common configuration
fuel_project::common::kernel_package: 'linux-generic-lts-vivid'
fuel_project::common::known_hosts:
  'jenkins':
    hosts:
     'review.fuel-infra.org':
       port: 29418
     'review.openstack.org':
       port: 29418
fuel_project::common::ldap: true
fuel_project::common::ssh_keys_groups:
  - 'ci_systems'
  - 'ci_team'
  - 'devops_team'

# jenkins slave configuration
fuel_project::jenkins::slave::http_share_iso: true

# sudo configuration
sudo::configs:
  'jenkins':
    'content': 'jenkins ALL=(ALL) NOPASSWD: ALL'
  'puppet':
    'content': 'jenkins ALL=(ALL) NOPASSWD: /usr/bin/puppet agent -vd --onetime --no-daemonize,/usr/bin/puppet agent -vd --onetime --no-daemonize --noop'
  'iptables-save':
    'content': '%mirantis ALL=(ALL) NOPASSWD: /sbin/iptables-save'
  'tcpdump':
    'content': '%mirantis ALL=(ALL) NOPASSWD: /usr/sbin/tcpdump'
  'umount':
    'content': '%mirantis ALL=(ALL) NOPASSWD: /bin/umount'
  'ebtables-ci-team':
    'content': '%ci ALL=(ALL) NOPASSWD: /sbin/ebtables --list'
  'dutop':
    'content': '%mirantis ALL=(ALL) NOPASSWD: /usr/bin/dutop ""'
  'dutop-libvirt':
    'content': '%mirantis ALL=(ALL) NOPASSWD: /usr/bin/dutop /var/lib/libvirt'

# sysctl configuration
sysctl::base::values:
  net.bridge.bridge-nf-call-iptables:
    value: '0'
  net.ipv4.ip_forward:
    value: '1'
  net.ipv4.tcp_syncookies:
    value: 1
  net.ipv4.tcp_window_scaling:
    value: 1
  net.ipv4.tcp_congestion_control:
    value: cubic
  net.ipv4.tcp_no_metrics_save:
    value: 1
  net.ipv4.tcp_moderate_rcvbuf:
    value: 1
  fs.inotify.max_user_instances:
    value: 1024

# other settings
libvirt::listen_addr: '0.0.0.0'
ssh::banner::content: "%{hiera('common::cislave::motd')}"
