---
classes:
  - '::fuel_project::jenkins::slave'
  - '::sudo'
  - '::sysctl::base'

fuel_project::jenkins::slave::verify_network_checker: true
fuel_project::jenkins::slave::install_docker: true
fuel_project::jenkins::slave::docker_config: |
    {
      "registry.domain.org": {
        "auth": "someMagicalAuthorization==",
        "email": "jenkins@mirantis.net"
      }
    }

# keep current sudo configuration
sudo::purge: false
sudo::config_file_replace: false

# https://bugs.launchpad.net/fuel/+bug/1458842
sudo::configs:
  'tcpdump':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/sbin/tcpdump'
  'dutop':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/bin/dutop ""'
  'dutop-libvirt':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/bin/dutop /var/lib/libvirt'

# enable hugepages
fuel_project::jenkins::slave::libvirt_hugepages: true


sysctl::base::values:
  net.bridge.bridge-nf-call-iptables:
    value: '0'
