---
classes:
  - '::fuel_project::jenkins::slave'
  - '::sudo'
  - '::sysctl::base'

fuel_project::jenkins::slave::verify_network_checker: true
fuel_project::jenkins::slave::install_docker: true
fuel_project::jenkins::slave::docker_config: |
    {
      "registry.domain.org": {
        "auth": "someMagicalAuthorization==",
        "email": "jenkins@mirantis.net"
      }
    }

# keep current sudo configuration
sudo::purge: false
sudo::config_file_replace: false

# https://bugs.launchpad.net/fuel/+bug/1458842
sudo::configs:
  'tcpdump':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/sbin/tcpdump'
  'dutop':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/bin/dutop ""'
  'dutop-libvirt':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/bin/dutop /var/lib/libvirt'

# apparmor rules
fuel_project::common::apparmor:
  /usr/sbin/libvirtd:
    ensure: disabled
  /usr/lib/libvirt/virt-aa-helper:
    ensure: disabled

# enable hugepages
fuel_project::common::kernel_parameters:
  transparent_hugepage:
    value: never
  hugepagesz:
    value: 1G
  hugepages:
    value: 256
  default_hugepagesz:
    value: 1G

fuel_project::common::files:
  /hugepages:
    ensure: directory

fuel_project::common::mounts:
  /hugepages:
    ensure: mounted
    atboot: true
    device: hugetlbfs
    fstype: hugetlbfs
    options: mode=1777
    require: File[/hugepages]

sysctl::base::values:
  net.bridge.bridge-nf-call-iptables:
    value: '0'
