---
classes:
  - '::openstackci::logserver'
  - '::fuel_project::common'
  - '::fuel_project::apps::seed'

openstackci::logserver::cron_jobs:
  'cron_gzip_logs':
    command: '/usr/bin/flock -xn /var/lock/cron_gzip_logs.lock find -O3 /srv/static/logs/ -not -name lost+found -type f -mmin +10 -not -name \*\[.-\]gz -not -name \*\[._-\]\[zZ\] \( -name \*.txt -or -name \*.html -or -name tmp\* -or -name \*.log \) -exec gzip \{\} \; 2>&1 | logger -t cron-gzip-logs'
    user: 'root'
    hour: '5'
    weekday: '6'
  'cron_rm_logs':
    command: '/usr/bin/flock -xn /var/lock/cron_rm_logs.lock find -O3 /srv/static/logs/ -not -name lost+found -mtime +120 -type f -exec rm \{\} \; -o \( -type d -empty -mtime +1 -exec rmdir \{\} \; \) 2>&1 | logger -t cron-rm-logs'
    user: 'root'
    hour: '7'
    weekday: '6'

openstackci::logserver::log_dir_paths:
  '/srv/static':
    path: '/srv/static'
  '/srv/static/logs':
    path: '/srv/static/logs'
  '/srv/static/logs/jenkins':
    path: '/srv/static/logs/jenkins'

openstackci::logserver::file_conditions_content: |
  - filename_pattern: ^.*\.txt(\.gz)?$
    filter: SevFilter
    view: HTMLView
  - filename_pattern: ^.*console\.html(\.gz)?$
    filter: SevFilter
    view: HTMLView
  - filename_pattern: ^.*$
    filter: NoFilter
    view: PassthroughView

openstackci::logserver::config_general_file_content: |
  filter = SevFilter
  view = HTMLView
  file_conditions = /etc/os_loganalyze/file_conditions.yaml
  generate_folder_index = true

fuel_project::apps::seed::shares:
  'jenkins':
    autoindex: true
    service_fqdn:
      - 'jenkins.test.local'
    path: '/srv/static/logs/jenkins/data'
    http_ro: true
    rsync_rw: true
    username: 'ci'
    ssh_authorized_keys:
      'ci':
        type: rsa
        key: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDoilVz2Pwv+6wS6bcAe4/Ss27sK6QEahXyXCv1lBczJX1A9L5+1kZ+kvKDLpew2U4R5ydwCxAGFIvl4YBbb5YrDt1pFmhGlwqUBLoWjJv90e+MF9rsIvdA4hFivmLh8w+gU9Ob7oy364kuOjsR79sfsBp4xo3bBwC9NYXiL2KxAvqt2YxGhL0IQJ4fZrFqRVg4Wo9b+ojhpEgHuDAVsPue1nXtsdK5xPKlcR3rVlx4FfLbg0uIKJIaO8wrWDYJAXpUHqbWKytAIjZosgqoiX5oHFptWdaPO80PzCk33Pvm9wLLnZvyWVnjc0D77fv6ODzwmUnqgnDdqQ6qORH5fE7D'

rssh::users:
  - 'ci:022:100000'

rsync::server::gid: 'root'
rsync::server::uid: 'root'
rsync::server::use_chroot: 'no'
rsync::server::use_xinetd: false
